package com.roomster.roomsterbackend.util.message;

public class MessageUtil {
    public static final String MSG_ROOM_NOT_FOUND = "Phòng không tồn tại !";
    public static final String MSG_BANK_METHOD_NOT_FOUND = "Phương thức thanh toán không tồn tại !";
    public static final String MSG_HOUSE_NOT_FOUND = "Nhà không tồn tại !";
    public static final String MSG_ORDER_NOT_FOUND = "Đơn không tồn tại !";
    public static final String MSG_SERVICE_NOT_FOUND = "Dịch vụ không tồn tại !";
    public static final String MSG_POST_NOT_FOUND = "Bài viết không tồn tại !";
    public static final String MSG_ROLE_NOT_FOUND = "Vai trò không tồn tại !";
    public static final String MSG_ROLE_EXITED = "Vai trò tồn tại !";
    public static final String MSG_OTP_CODE_INCORRECT = "Rất tiếc! Mã OTP của bạn không chính xác.";
    public static final String MSG_OTP_CODE_CORRECT = "Mã OTP của bạn chính xác.";
    public static final String MSG_WISHLIST_ITEM_EXITED = "Danh sách yêu thích đã tồn tại bài viết";
    public static final String MSG_CITY_NOT_FOUND = "Thành phố không tồn tại !";
    public static final String MSG_WARD_NOT_FOUND = "Phường không tồn tại !";
    public static final String MSG_TENANT_NOT_CHECK = "Bạn chưa chọn khách thuê phòng nào !";
    public static final String MSG_DISTRICT_NOT_FOUND = "Quận không tồn tại !";
    public static final String MSG_ID_FORMAT_INVALID = "Mã sai định dạng !";
    public static final String MSG_PHONE_NUMBER_FORMAT_INVALID = "Mã sai định dạng !";
    public static final String MSG_ADD_SUCCESS = "Thêm mới thành công !";
    public static final String MSG_UPDATE_SUCCESS = "Cập nhật thành công !";
    public static final String MSG_DELETE_SUCCESS = "Xóa thành công !";
    public static final String MSG_SYSTEM_ERROR = "Lỗi hệ thống vui lòng thử lại sau !";
    public static final String MSG_TENANT_NOT_FOUND = "Không tìm thấy khách thuê phòng !";
    public static final String MSG_ROOM_NOT_VALID = "Phòng không phù hợp !";
    public static final String MSG_HOUSE_EXISTS = "Thông tin nhà đã tồn tại !";
    public static final String MSG_ROOM_EXISTS = "Thông tin phòng đã tồn tại !";
    public static final String MSG_TENANT_EXISTS = "Thông tin khách ở đã tồn tại !";
    public static final String MSG_SERVICE_EXISTS = "Thông tin dịch vụ đã tồn tại !";
    public static final String MSG_ROOM_IS_FULL = "Phòng này đã đủ người !";
    public static final String MSG_ROOM_IS_EMPTY = "Trạng thái phòng này chưa thuê không thể thêm dịch vụ điện nước!";

    public static final String MSG_PHONE_NUMBER_IS_EXITED = "Số điện thoại đã tồn tại. Vui lòng nhập số điện thoại mới";
    public static final String MSG_PHONE_NUMBER_NOT_FOUND = "Số điện thoại không đúng. Vui lòng nhập số điện thoại mới";
    public static final String MSG_PHONE_NUMBER_CONFIRM_NOT_VALID = "Số điện thoại xác thực không đúng. Vui lòng nhập số điện thoại mới";
    public static final String MSG_OTP_DELIVERED = "Mã xác nhận đã được gửi đến số điện thoại của bạn. Vui lòng nhập mã vào bên dưới để tiếp tục";
    public static final String MSG_OTP_FAILED = "Rất tiếc! Không thể gửi mã xác nhận. Vui lòng thử lại để tiếp tục";
    public static final String MSG_USER_BY_TOKEN_NOT_FOUND = "Không thể tìm thấy người dùng với token !";
    public static final String MSG_UP_ROLE_MANAGE_SUCCESS = "Xác thực số điện thoại thành công !";
    public static final String MSG_REGISTER_SUCCESS = "Đăng ký thành công !";
    public static final String MSG_REGISTER_FAIL = "Đăng ký tài khoản không thành công !";
    public static final String MSG_OK = "OK";
    public static final String MSG_CANCEL = "Cancel";

    public static final String MSG_PROCESS_TRANSACTION_PAYMENT_FAIL = "Xin lỗi, giao dịch thanh toán của bạn không thành công.";
    public static final String MSG_PROCESS_TRANSACTION_PAYMENT_SUCCESS = "Cảm ơn bạn, giao dịch thanh toán thành công !";
    public static final String MSG_PAYMENT_NOT_FOUND = "Giao dịch thanh toán không tìm thấy.";
    public static final String MSG_AUTHENTICATION_FAIL = "Đăng nhập không thành công. Vui lòng kiểm tra số điện thoại hoặc mật khẩu.";
    public static final String MSG_TRANSACTION_SERVICE_SUCCESS_WITH_SMS = "Giao dich thanh toán dịch vụ thành công, Vui lòng kiểm tra SMS để xem chi tiết ";
    public static final String MSG_TRANSACTION_EXTENSION_SERVICE_SUCCESS_WITH_SMS = "Giao dich thanh toán gia hạn dịch vụ thành công, Vui lòng kiểm tra SMS để xem chi tiết ";
    public static final String MSG_TRANSACTION_SERVICE_SUCCESS_WITHOUT_SMS = "Giao dich thanh toán dịch vụ thành công. Lỗi gửi SMS! ";
    public static final String MSG_TRANSACTION_EXTENSION_SERVICE_SUCCESS_WITHOUT_SMS = "Giao dich thanh toán gia hạn dịch vụ thành công. Lỗi gửi SMS! ";
    public static final String MSG_BALANCE_NOT_ENOUGH = "Hiện tại, Số dư của bạn không đủ để thực hiện giao dịch.";
    public static final String MSG_SERVICE_PACKAGE_IS_EXPIRED = "Gói dịch vụ của bạn đã hết hạn, vui lòng gia hạn hoặc mua gói mới để sử dụng tính năng";
    public static final String MSG_SERVICE_PACKAGE_NOT_FOUND = "Vui lòng mua gói mới để sử dụng tính năng";
    public static final String MSG_SEND_MAIL_SUCCESS = "Gửi mail thành công !";
    public static final String MSG_SEND_MAIL_FAILURE = "Gửi mail Thất bại !";
    public static final String MSG_ORDER_PAYMENT_NOT_FOUND = "Không có phòng cần gửi bill";
    public static final String MSG_METHOD_PAYMENT_NOT_FOUND = "Không tìm thấy phương thức thanh toán nào !";
    public static final String MSG_ORDER_PAYMENT = "Đơn tháng này đã thanh toán không thể thêm mới hay chỉnh sửa";    public static final String MSG_USER_NOT_FOUND = "Người dùng không tìm thấy !";
}
